services:
    web:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - node
    node:
        image: node:lts-alpine3.17
        ports:
            - '8081:80'
        volumes:
            - './:/app'
        command: --watch --enable-source-maps /app/public/dist/server.js
        env_file:
            - .env
        links:
            - db
        depends_on:
            db:
                condition: "service_healthy"
    db:
        image: mysql:latest
        ports:
            - '8082:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root
            start_period: 5s
            interval: 5s
        volumes:
            - './docker/mysql:/var/lib/mysql'
